name: 'CSG - PR Labels '
description: 'Manage pull request flags as a labels'
inputs:
  pull_request:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  label:
    description: 'The new label to add to the current pull request'
    required: false
  label_remove:
    description: 'The label to remove in the current pull request'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
